name: 'pwsh-module-publish'
description: 'Publishes a PowerShell Module using PowerShellGet 2'
inputs:
  moduleName:
    description: 'Name of PowerShell Module to Publish'
    required: true

  nuGetApiKey:
    description: 'PowerShell Gallery NuGetApiKey'
    required: true

  testGallery:
    description: 'Publish to Posh Test Gallery'
    required: false

runs:
  using: composite
  steps:
  - name: Download Build Output
    uses: actions/download-artifact@v2

  - uses: russellds/Actions/install-requiredmodules@v1
    with:
      requiredModules-path: ${{ github.workspace }}/RequiredModules/RequiredModules.psd1

  - if: ${{ inputs.testGallery != 0 }}
    name: 'Publish PowerShell Module to the Posh Test Gallery'
    run: ${{ github.action_path }}/lib/main.ps1 -ModuleName '${{ inputs.moduleName }}' -NuGetApiKey '${{ inputs.nuGetApiKey }}' -TestGallery
    shell: pwsh

  - if: ${{ inputs.testGallery == 0 }}
    name: 'Publish PowerShell Module to the Powershell Gallery'
    run: ${{ github.action_path }}/lib/main.ps1 -ModuleName '${{ inputs.moduleName }}' -NuGetApiKey '${{ inputs.nuGetApiKey }}'
    shell: pwsh
